### ISSUE TITLE
Fix imports

### ISSUE THREAD

**Issue by bmsrangel** [lucas404x/repositories-list#17]
Fix imports to match the recommended standard.

**Comment by noti0nS** [comment]
We can divide this task

**Comment by bmsrangel** [comment]
> We can divide this task

Sure! I have a lib to indicate that helps with this task. It's called "dart-import" (https://marketplace.visualstudio.com/items?itemName=luanpotter.dart-import).

Take a look in its description and let me know if you have any questions.
