### ISSUE TITLE
Delegate actions on widgets

### ISSUE THREAD

**Issue by bmsrangel** [lucas404x/repositories-list#20]
Some widgets have an action hard coded on them. A suggestion is to delegate their action to their parent widget.
Widget list:
* shared/widgets/profile_button
* shared/widgets/repository_card

**Comment by noti0nS** [comment]
The problem was solved with this commit: https://github.com/lucas404x/repositories-list/commit/ec475c2123434f6e9325baa6cd01f9a8b9d0e46e
