### ISSUE TITLE
Delete the "0"  when is return null in some widgets at RepositoryInfoPage

### ISSUE THREAD

**Issue by noti0nS** [lucas404x/repositories-list#24]
I think "0" is a wrong information...
What if replace "0" to "No info provided" or anything else? I think better

**Comment by bmsrangel** [comment]
Well, considering it's a "count", and all repositories have the "watch" and the "star" properties, if the event of one of these values comes as "null", they probably are 0. I believe we can remove this "safety" and check if it will break the app once.

**Comment by noti0nS** [comment]
Yeah, I agree
